
create table if not exists people (
                                      id INT,
                                      first_name VARCHAR(50),
                                      last_name VARCHAR(50),
                                      full_name VARCHAR(50),
                                      email VARCHAR(50),
                                      gender VARCHAR(50),
                                      ip_address VARCHAR(20),
                                      ssn VARCHAR(50)
);
ALTER TABLE people ADD CONSTRAINT people_pk PRIMARY KEY (id)

CREATE TABLE orders(
                       order_id serial primary key,
                       product_name varchar(50),
                       person_id integer
);


ALTER TABLE orders ADD CONSTRAINT orders_person_id_fk
    FOREIGN KEY (person_id) REFERENCES people (id);

insert into orders (order_id, product_name, person_id) values (1, 'Bread - Italian Sesame Poly', 292);
insert into orders (order_id, product_name, person_id) values (2, 'Longos - Grilled Chicken With', 495);
insert into orders (order_id, product_name, person_id) values (3, 'Island Oasis - Peach Daiquiri', 50);
insert into orders (order_id, product_name, person_id) values (4, 'Rye Special Old', 375);
insert into orders (order_id, product_name, person_id) values (5, 'Turkey Leg With Drum And Thigh', 238);
insert into orders (order_id, product_name, person_id) values (6, 'Wine - Spumante Bambino White', 443);
insert into orders (order_id, product_name, person_id) values (7, 'Apricots Fresh', 72);
insert into orders (order_id, product_name, person_id) values (8, 'Beer - Rickards Red', 744);
insert into orders (order_id, product_name, person_id) values (9, 'Shrimp - Black Tiger 8 - 12', 495);
insert into orders (order_id, product_name, person_id) values (10, 'Cheese - Goat', 931);
insert into orders (order_id, product_name, person_id) values (11, 'Soup - Knorr, Ministrone', 515);
insert into orders (order_id, product_name, person_id) values (12, 'Cocoa Butter', 132);
insert into orders (order_id, product_name, person_id) values (13, 'Tomato - Peeled Italian Canned', 163);
insert into orders (order_id, product_name, person_id) values (14, 'Pepsi - Diet, 355 Ml', 500);
insert into orders (order_id, product_name, person_id) values (15, 'Wine - Red, Marechal Foch', 513);
insert into orders (order_id, product_name, person_id) values (16, 'Pepper - Black, Crushed', 660);
insert into orders (order_id, product_name, person_id) values (17, 'Bread - Kimel Stick Poly', 619);
insert into orders (order_id, product_name, person_id) values (18, 'Beef - Bresaola', 235);
insert into orders (order_id, product_name, person_id) values (19, 'Ham - Procutinni', 968);
insert into orders (order_id, product_name, person_id) values (20, 'Wine - Red, Gallo, Merlot', 833);
insert into orders (order_id, product_name, person_id) values (21, 'Sugar - Invert', 419);
insert into orders (order_id, product_name, person_id) values (22, 'Cheese - Blue', 968);
insert into orders (order_id, product_name, person_id) values (23, 'Vector Energy Bar', 97);
insert into orders (order_id, product_name, person_id) values (24, 'Sesame Seed Black', 184);
insert into orders (order_id, product_name, person_id) values (25, 'Sesame Seed', 999);
insert into orders (order_id, product_name, person_id) values (26, 'Truffle Cups Green', 312);
insert into orders (order_id, product_name, person_id) values (27, 'Table Cloth 144x90 White', 463);
insert into orders (order_id, product_name, person_id) values (28, 'Bar Nature Valley', 53);

insert into orders (order_id, product_name, person_id) values (30, 'Cheese - Le Cru Du Clocher', 123);
insert into orders (order_id, product_name, person_id) values (31, 'Sprite - 355 Ml', 196);
insert into orders (order_id, product_name, person_id) values (32, 'Bar - Sweet And Salty Chocolate', 919);
insert into orders (order_id, product_name, person_id) values (33, 'Sausage - Chorizo', 988);
insert into orders (order_id, product_name, person_id) values (34, 'Bread - White Mini Epi', 234);
insert into orders (order_id, product_name, person_id) values (35, 'Chocolate - Milk', 81);
insert into orders (order_id, product_name, person_id) values (36, 'Bar Mix - Lemon', 689);
insert into orders (order_id, product_name, person_id) values (37, 'Oil - Sesame', 436);
insert into orders (order_id, product_name, person_id) values (38, 'Mussels - Frozen', 900);
insert into orders (order_id, product_name, person_id) values (39, 'Bread Roll Foccacia', 424);
insert into orders (order_id, product_name, person_id) values (40, 'Oil - Macadamia', 506);
insert into orders (order_id, product_name, person_id) values (41, 'Allspice - Jamaican', 978);
insert into orders (order_id, product_name, person_id) values (42, 'Flour Pastry Super Fine', 768);
insert into orders (order_id, product_name, person_id) values (43, 'Pork - European Side Bacon', 59);
insert into orders (order_id, product_name, person_id) values (44, 'Veal Inside - Provimi', 455);
insert into orders (order_id, product_name, person_id) values (45, 'Crab - Dungeness, Whole', 670);
insert into orders (order_id, product_name, person_id) values (46, 'Veal - Tenderloin, Untrimmed', 775);
insert into orders (order_id, product_name, person_id) values (47, 'Filter - Coffee', 790);
insert into orders (order_id, product_name, person_id) values (48, 'Shrimp - 16/20, Iqf, Shell On', 151);
insert into orders (order_id, product_name, person_id) values (49, 'Squash - Pepper', 300);
insert into orders (order_id, product_name, person_id) values (50, 'Coffee Cup 16oz Foam', 83);
insert into orders (order_id, product_name, person_id) values (51, 'Poppy Seed', 227);
insert into orders (order_id, product_name, person_id) values (52, 'Bagel - Plain', 384);
insert into orders (order_id, product_name, person_id) values (53, 'Blue Curacao - Marie Brizard', 177);
insert into orders (order_id, product_name, person_id) values (54, 'Liqueur - Melon', 49);
insert into orders (order_id, product_name, person_id) values (55, 'Bread - Focaccia Quarter', 337);
insert into orders (order_id, product_name, person_id) values (56, 'Bread - Roll, Soft White Round', 729);
insert into orders (order_id, product_name, person_id) values (57, 'Chicken - Ground', 207);
insert into orders (order_id, product_name, person_id) values (58, 'Slt - Individual Portions', 573);
insert into orders (order_id, product_name, person_id) values (59, 'Fib N9 - Prague Powder', 43);
insert into orders (order_id, product_name, person_id) values (60, 'Beef - Tenderlion, Center Cut', 893);
insert into orders (order_id, product_name, person_id) values (61, 'Asparagus - White, Fresh', 743);
insert into orders (order_id, product_name, person_id) values (62, 'Lid Coffee Cup 8oz Blk', 728);
insert into orders (order_id, product_name, person_id) values (63, 'Wine - Ruffino Chianti', 759);
insert into orders (order_id, product_name, person_id) values (64, 'Wine - Vouvray Cuvee Domaine', 717);
insert into orders (order_id, product_name, person_id) values (65, 'Fireball Whisky', 652);
insert into orders (order_id, product_name, person_id) values (66, 'Chocolate - Pistoles, White', 601);
insert into orders (order_id, product_name, person_id) values (67, 'Wine - Rosso Del Veronese Igt', 852);
insert into orders (order_id, product_name, person_id) values (68, 'Dawn Professionl Pot And Pan', 367);
insert into orders (order_id, product_name, person_id) values (69, 'Bay Leaf Ground', 937);
insert into orders (order_id, product_name, person_id) values (70, 'Broom And Broom Rack White', 102);
insert into orders (order_id, product_name, person_id) values (71, 'Tomatoes - Vine Ripe, Yellow', 70);
insert into orders (order_id, product_name, person_id) values (72, 'Whmis Spray Bottle Graduated', 4);
insert into orders (order_id, product_name, person_id) values (73, 'Vinegar - Balsamic, White', 9);
insert into orders (order_id, product_name, person_id) values (74, 'Juice - Mango', 170);
insert into orders (order_id, product_name, person_id) values (75, 'Tea - Herbal Sweet Dreams', 406);
insert into orders (order_id, product_name, person_id) values (76, 'Pork - Back, Long Cut, Boneless', 552);
insert into orders (order_id, product_name, person_id) values (77, 'Shrimp - Prawn', 351);
insert into orders (order_id, product_name, person_id) values (78, 'Teriyaki Sauce', 603);
insert into orders (order_id, product_name, person_id) values (79, 'Champagne - Brights, Dry', 203);
insert into orders (order_id, product_name, person_id) values (80, 'Chicken - White Meat, No Tender', 251);
insert into orders (order_id, product_name, person_id) values (81, 'Ham - Cooked Bayonne Tinned', 221);
insert into orders (order_id, product_name, person_id) values (82, 'Red Currants', 900);
insert into orders (order_id, product_name, person_id) values (83, 'Tequila Rose Cream Liquor', 179);
insert into orders (order_id, product_name, person_id) values (84, 'Onions - White', 32);
insert into orders (order_id, product_name, person_id) values (85, 'Ice Cream Bar - Hageen Daz To', 196);
insert into orders (order_id, product_name, person_id) values (86, 'Nougat - Paste / Cream', 298);
insert into orders (order_id, product_name, person_id) values (87, 'Alize Sunset', 48);
insert into orders (order_id, product_name, person_id) values (88, 'Cheese - Valancey', 242);
insert into orders (order_id, product_name, person_id) values (89, 'Veal - Shank, Pieces', 380);
insert into orders (order_id, product_name, person_id) values (90, 'Coconut Milk - Unsweetened', 614);
insert into orders (order_id, product_name, person_id) values (91, 'Cheese - Provolone', 697);
insert into orders (order_id, product_name, person_id) values (92, 'Oil - Peanut', 273);
insert into orders (order_id, product_name, person_id) values (93, 'Mushroom - Chanterelle Frozen', 686);
insert into orders (order_id, product_name, person_id) values (94, 'Cheese - Bakers Cream Cheese', 398);
insert into orders (order_id, product_name, person_id) values (95, 'Wine - Red, Mouton Cadet', 340);
insert into orders (order_id, product_name, person_id) values (96, 'Wine - Crozes Hermitage E.', 610);
insert into orders (order_id, product_name, person_id) values (97, 'Coffee - Dark Roast', 621);
insert into orders (order_id, product_name, person_id) values (98, 'Ocean Spray - Kiwi Strawberry', 372);
insert into orders (order_id, product_name, person_id) values (99, 'Butter - Salted', 842);
insert into orders (order_id, product_name, person_id) values (100, 'Chocolate Bar - Coffee Crisp', 861);
insert into orders (order_id, product_name, person_id) values (101, 'Vodka - Hot, Lnferno', 313);
insert into orders (order_id, product_name, person_id) values (102, 'Pate - Peppercorn', 902);
insert into orders (order_id, product_name, person_id) values (103, 'Wine - Sawmill Creek Autumn', 548);
insert into orders (order_id, product_name, person_id) values (104, 'Garbage Bags - Clear', 575);
insert into orders (order_id, product_name, person_id) values (105, 'Beer - Fruli', 783);
insert into orders (order_id, product_name, person_id) values (106, 'Pate - Liver', 652);
insert into orders (order_id, product_name, person_id) values (107, 'Beef - Ox Tongue, Pickled', 118);
insert into orders (order_id, product_name, person_id) values (108, 'Artichokes - Knobless, White', 591);
insert into orders (order_id, product_name, person_id) values (109, 'Grapes - Red', 767);
insert into orders (order_id, product_name, person_id) values (110, 'Chocolate - Mi - Amere Semi', 981);
insert into orders (order_id, product_name, person_id) values (111, 'Dehydrated Kelp Kombo', 499);
insert into orders (order_id, product_name, person_id) values (112, 'Horseradish - Prepared', 626);
insert into orders (order_id, product_name, person_id) values (113, 'Shrimp - Baby, Cold Water', 676);
insert into orders (order_id, product_name, person_id) values (114, 'Cookies - Fortune', 681);
insert into orders (order_id, product_name, person_id) values (115, 'Chutney Sauce - Mango', 392);
insert into orders (order_id, product_name, person_id) values (116, 'Sole - Fillet', 371);
insert into orders (order_id, product_name, person_id) values (117, 'Pork Salted Bellies', 803);
insert into orders (order_id, product_name, person_id) values (118, 'Mussels - Cultivated', 499);
insert into orders (order_id, product_name, person_id) values (119, 'Water - Aquafina Vitamin', 140);
insert into orders (order_id, product_name, person_id) values (120, 'Limes', 757);
insert into orders (order_id, product_name, person_id) values (121, 'Star Fruit', 96);
insert into orders (order_id, product_name, person_id) values (122, 'Salt - Rock, Course', 852);
insert into orders (order_id, product_name, person_id) values (123, 'Truffle Cups - Red', 779);
insert into orders (order_id, product_name, person_id) values (124, 'Vegetable - Base', 740);
insert into orders (order_id, product_name, person_id) values (125, 'Spring Roll Veg Mini', 434);
insert into orders (order_id, product_name, person_id) values (126, 'Beef Tenderloin Aaa', 942);
insert into orders (order_id, product_name, person_id) values (127, 'Turkey Leg With Drum And Thigh', 361);
insert into orders (order_id, product_name, person_id) values (128, 'Table Cloth 54x54 Colour', 575);
insert into orders (order_id, product_name, person_id) values (129, 'Anisette - Mcguiness', 408);
insert into orders (order_id, product_name, person_id) values (130, 'Wine - Vineland Estate Semi - Dry', 568);
insert into orders (order_id, product_name, person_id) values (131, 'Ecolab Digiclean Mild Fm', 218);
insert into orders (order_id, product_name, person_id) values (132, 'Veal - Knuckle', 363);
insert into orders (order_id, product_name, person_id) values (133, 'Flour - Rye', 455);
insert into orders (order_id, product_name, person_id) values (134, 'Vegetable - Base', 191);
insert into orders (order_id, product_name, person_id) values (135, 'Daikon Radish', 358);
insert into orders (order_id, product_name, person_id) values (136, 'Chicken - White Meat, No Tender', 110);
insert into orders (order_id, product_name, person_id) values (137, 'Flower - Commercial Spider', 505);
insert into orders (order_id, product_name, person_id) values (138, 'Spice - Montreal Steak Spice', 202);
insert into orders (order_id, product_name, person_id) values (139, 'Bread - 10 Grain', 516);
insert into orders (order_id, product_name, person_id) values (140, 'Cookies - Englishbay Oatmeal', 870);
insert into orders (order_id, product_name, person_id) values (141, 'Bacardi Raspberry', 99);
insert into orders (order_id, product_name, person_id) values (142, 'Wine - Toasted Head', 392);
insert into orders (order_id, product_name, person_id) values (143, 'Rum - Cream, Amarula', 378);
insert into orders (order_id, product_name, person_id) values (144, 'Melon - Cantaloupe', 558);
insert into orders (order_id, product_name, person_id) values (145, 'Aspic - Amber', 523);
insert into orders (order_id, product_name, person_id) values (146, 'Bamboo Shoots - Sliced', 760);
insert into orders (order_id, product_name, person_id) values (147, 'Cape Capensis - Fillet', 84);
insert into orders (order_id, product_name, person_id) values (148, 'Rum - Light, Captain Morgan', 443);
insert into orders (order_id, product_name, person_id) values (149, 'Hipnotiq Liquor', 373);
insert into orders (order_id, product_name, person_id) values (150, 'Bacardi Limon', 40);
insert into orders (order_id, product_name, person_id) values (151, 'Bread - Bagels, Plain', 26);
insert into orders (order_id, product_name, person_id) values (152, 'Longos - Chicken Caeser Salad', 399);
insert into orders (order_id, product_name, person_id) values (153, 'Lettuce - Green Leaf', 439);
insert into orders (order_id, product_name, person_id) values (154, 'Tart - Raisin And Pecan', 253);
insert into orders (order_id, product_name, person_id) values (155, 'Worcestershire Sauce', 860);
insert into orders (order_id, product_name, person_id) values (156, 'Tuna - Loin', 676);
insert into orders (order_id, product_name, person_id) values (157, 'Thyme - Dried', 558);
insert into orders (order_id, product_name, person_id) values (158, 'Pork - Backs - Boneless', 116);
insert into orders (order_id, product_name, person_id) values (159, 'Trueblue - Blueberry Cranberry', 937);
insert into orders (order_id, product_name, person_id) values (161, 'Soup - Campbells, Creamy', 105);
insert into orders (order_id, product_name, person_id) values (162, 'Magnotta - Bel Paese White', 569);
insert into orders (order_id, product_name, person_id) values (163, 'Pasta - Penne, Lisce, Dry', 176);
insert into orders (order_id, product_name, person_id) values (164, 'Chicken - Leg, Boneless', 955);
insert into orders (order_id, product_name, person_id) values (165, 'Muffin - Mix - Mango Sour Cherry', 583);
insert into orders (order_id, product_name, person_id) values (166, 'Nutmeg - Ground', 65);
insert into orders (order_id, product_name, person_id) values (167, 'Muffin Batt - Ban Dream Zero', 819);
insert into orders (order_id, product_name, person_id) values (168, 'Cheese - Ricotta', 320);
insert into orders (order_id, product_name, person_id) values (169, 'Soup - Knorr, Chicken Noodle', 811);
insert into orders (order_id, product_name, person_id) values (170, 'Chicken Breast Halal', 624);
insert into orders (order_id, product_name, person_id) values (171, 'Soup - Verve - Chipotle Chicken', 854);
insert into orders (order_id, product_name, person_id) values (172, 'Pasta - Orzo, Dry', 851);
insert into orders (order_id, product_name, person_id) values (173, 'Beans - Fine', 641);
insert into orders (order_id, product_name, person_id) values (174, 'Gelatine Leaves - Bulk', 935);
insert into orders (order_id, product_name, person_id) values (175, 'Milk Powder', 635);
insert into orders (order_id, product_name, person_id) values (176, 'Coffee - Frthy Coffee Crisp', 554);
insert into orders (order_id, product_name, person_id) values (177, 'Snapple Raspberry Tea', 133);
insert into orders (order_id, product_name, person_id) values (178, 'Waffle Stix', 173);
insert into orders (order_id, product_name, person_id) values (179, 'Juice - Lemon', 305);
insert into orders (order_id, product_name, person_id) values (180, 'Slt - Individual Portions', 213);
insert into orders (order_id, product_name, person_id) values (181, 'Raspberries - Fresh', 317);
insert into orders (order_id, product_name, person_id) values (182, 'Steampan - Foil', 182);
insert into orders (order_id, product_name, person_id) values (183, 'Tahini Paste', 383);
insert into orders (order_id, product_name, person_id) values (184, 'Crackers - Water', 432);
insert into orders (order_id, product_name, person_id) values (185, 'Cookie Dough - Oatmeal Rasin', 286);
insert into orders (order_id, product_name, person_id) values (186, 'Puff Pastry - Sheets', 960);
insert into orders (order_id, product_name, person_id) values (187, 'Wine - Guy Sage Touraine', 66);
insert into orders (order_id, product_name, person_id) values (188, 'Chickensplit Half', 833);
insert into orders (order_id, product_name, person_id) values (189, 'Chicken - Leg, Fresh', 619);
insert into orders (order_id, product_name, person_id) values (190, 'Syrup - Monin - Passion Fruit', 659);
insert into orders (order_id, product_name, person_id) values (191, 'Wine - Riesling Dr. Pauly', 392);
insert into orders (order_id, product_name, person_id) values (192, 'Paper Cocktail Umberlla 80 - 180', 170);
insert into orders (order_id, product_name, person_id) values (193, 'Soup - Knorr, Chicken Gumbo', 70);
insert into orders (order_id, product_name, person_id) values (194, 'Beer - Upper Canada Light', 846);
insert into orders (order_id, product_name, person_id) values (195, 'Mangostein', 128);
insert into orders (order_id, product_name, person_id) values (196, 'Loquat', 66);
insert into orders (order_id, product_name, person_id) values (197, 'Pie Pecan', 641);
insert into orders (order_id, product_name, person_id) values (198, 'Pears - Bosc', 387);
insert into orders (order_id, product_name, person_id) values (199, 'Table Cloth 54x72 White', 820);
insert into orders (order_id, product_name, person_id) values (200, 'Flour - Semolina', 253);
insert into orders (order_id, product_name, person_id) values (201, 'Lemonade - Natural, 591 Ml', 628);
insert into orders (order_id, product_name, person_id) values (202, 'Nutmeg - Ground', 162);
insert into orders (order_id, product_name, person_id) values (203, 'Bacardi Limon', 777);
insert into orders (order_id, product_name, person_id) values (204, 'Sproutsmustard Cress', 515);
insert into orders (order_id, product_name, person_id) values (205, 'Soup - Campbells, Cream Of', 634);
insert into orders (order_id, product_name, person_id) values (206, 'Bread - Multigrain', 778);
insert into orders (order_id, product_name, person_id) values (207, 'Carbonated Water - Blackberry', 424);
insert into orders (order_id, product_name, person_id) values (208, 'Onions - Pearl', 618);
insert into orders (order_id, product_name, person_id) values (209, 'Mayonnaise', 693);
insert into orders (order_id, product_name, person_id) values (210, 'Oneshot Automatic Soap System', 219);
insert into orders (order_id, product_name, person_id) values (211, 'Bandage - Fexible 1x3', 119);
insert into orders (order_id, product_name, person_id) values (212, 'Corn - Mini', 717);
insert into orders (order_id, product_name, person_id) values (213, 'Sambuca - Ramazzotti', 605);
insert into orders (order_id, product_name, person_id) values (214, 'Butter Ripple - Phillips', 565);
insert into orders (order_id, product_name, person_id) values (215, 'Beef Tenderloin Aaa', 870);
insert into orders (order_id, product_name, person_id) values (216, 'Cheese - Marble', 732);
insert into orders (order_id, product_name, person_id) values (217, 'Chocolate - Dark Callets', 648);
insert into orders (order_id, product_name, person_id) values (218, 'Wine - Cotes Du Rhone Parallele', 120);
insert into orders (order_id, product_name, person_id) values (219, 'Bar Nature Valley', 608);
insert into orders (order_id, product_name, person_id) values (220, 'Nut - Almond, Blanched, Sliced', 825);
insert into orders (order_id, product_name, person_id) values (221, 'Salmon Steak - Cohoe 6 Oz', 284);
insert into orders (order_id, product_name, person_id) values (222, 'Parsley - Fresh', 33);
insert into orders (order_id, product_name, person_id) values (223, 'Tia Maria', 859);
insert into orders (order_id, product_name, person_id) values (224, 'Carrots - Mini Red Organic', 797);
insert into orders (order_id, product_name, person_id) values (225, 'Crab Brie In Phyllo', 306);
insert into orders (order_id, product_name, person_id) values (226, 'Sugar - Icing', 278);
insert into orders (order_id, product_name, person_id) values (227, 'Peas - Pigeon, Dry', 691);
insert into orders (order_id, product_name, person_id) values (228, 'Wine - Red, Cooking', 173);
insert into orders (order_id, product_name, person_id) values (229, 'Wine - White, Pinot Grigio', 863);
insert into orders (order_id, product_name, person_id) values (230, 'Sping Loaded Cup Dispenser', 28);
insert into orders (order_id, product_name, person_id) values (231, 'Mushroom Morel Fresh', 351);
insert into orders (order_id, product_name, person_id) values (232, 'Sage Derby', 476);
insert into orders (order_id, product_name, person_id) values (233, 'Cake - Dulce De Leche', 688);
insert into orders (order_id, product_name, person_id) values (234, 'Red Pepper Paste', 834);
insert into orders (order_id, product_name, person_id) values (235, 'Coffee - Ristretto Coffee Capsule', 933);
insert into orders (order_id, product_name, person_id) values (236, 'Higashimaru Usukuchi Soy', 905);
insert into orders (order_id, product_name, person_id) values (237, 'Vinegar - Champagne', 701);
insert into orders (order_id, product_name, person_id) values (238, 'Pectin', 189);
insert into orders (order_id, product_name, person_id) values (239, 'Aspic - Clear', 662);
insert into orders (order_id, product_name, person_id) values (240, 'Puree - Kiwi', 42);
insert into orders (order_id, product_name, person_id) values (241, 'Halibut - Fletches', 15);
insert into orders (order_id, product_name, person_id) values (242, 'Shrimp - Black Tiger 16/20', 727);
insert into orders (order_id, product_name, person_id) values (243, 'Vaccum Bag 10x13', 961);
insert into orders (order_id, product_name, person_id) values (244, 'Lettuce - Escarole', 366);
insert into orders (order_id, product_name, person_id) values (245, 'Sproutsmustard Cress', 605);
insert into orders (order_id, product_name, person_id) values (246, 'Beef Tenderloin Aaa', 149);
insert into orders (order_id, product_name, person_id) values (247, 'Lid - High Heat, Super Clear', 178);
insert into orders (order_id, product_name, person_id) values (248, 'Egg Patty Fried', 586);
insert into orders (order_id, product_name, person_id) values (249, 'Smirnoff Green Apple Twist', 257);
insert into orders (order_id, product_name, person_id) values (250, 'Olives - Black, Pitted', 547);
insert into orders (order_id, product_name, person_id) values (251, 'Shark - Loin', 447);
insert into orders (order_id, product_name, person_id) values (252, 'Tomato - Tricolor Cherry', 960);
insert into orders (order_id, product_name, person_id) values (253, 'Milk Powder', 146);
insert into orders (order_id, product_name, person_id) values (254, 'Pear - Packum', 207);
insert into orders (order_id, product_name, person_id) values (255, 'Steampan - Foil', 95);
insert into orders (order_id, product_name, person_id) values (256, 'Chestnuts - Whole,canned', 499);
insert into orders (order_id, product_name, person_id) values (257, 'Tart - Pecan Butter Squares', 30);
insert into orders (order_id, product_name, person_id) values (258, 'Cookie - Oatmeal', 497);
insert into orders (order_id, product_name, person_id) values (259, 'Cheese - Ricotta', 549);
insert into orders (order_id, product_name, person_id) values (260, 'French Pastries', 749);
insert into orders (order_id, product_name, person_id) values (261, 'Wine - Stoneliegh Sauvignon', 601);
insert into orders (order_id, product_name, person_id) values (262, 'Cookie - Oatmeal', 415);
insert into orders (order_id, product_name, person_id) values (263, 'Wine - Fume Blanc Fetzer', 625);
insert into orders (order_id, product_name, person_id) values (264, 'Oil - Hazelnut', 122);
insert into orders (order_id, product_name, person_id) values (265, 'Buttons', 484);
insert into orders (order_id, product_name, person_id) values (266, 'Yogurt - Strawberry, 175 Gr', 448);
insert into orders (order_id, product_name, person_id) values (267, 'Wine - Duboeuf Beaujolais', 35);
insert into orders (order_id, product_name, person_id) values (268, 'Syrup - Monin, Irish Cream', 456);

insert into orders (order_id, product_name, person_id) values (270, 'Tandoori Curry Paste', 216);
insert into orders (order_id, product_name, person_id) values (271, 'Pork - Butt, Boneless', 101);
insert into orders (order_id, product_name, person_id) values (272, 'Cookie Dough - Chocolate Chip', 23);
insert into orders (order_id, product_name, person_id) values (273, 'Gooseberry', 223);
insert into orders (order_id, product_name, person_id) values (274, 'Corn Meal', 621);
insert into orders (order_id, product_name, person_id) values (275, 'Chocolate - Mi - Amere Semi', 897);
insert into orders (order_id, product_name, person_id) values (276, 'Sage - Ground', 788);
insert into orders (order_id, product_name, person_id) values (277, 'Duck - Breast', 498);
insert into orders (order_id, product_name, person_id) values (278, 'Wine - Red, Pelee Island Merlot', 127);
insert into orders (order_id, product_name, person_id) values (279, 'Cinnamon - Stick', 473);
insert into orders (order_id, product_name, person_id) values (280, 'Trout - Rainbow, Frozen', 692);
insert into orders (order_id, product_name, person_id) values (281, 'Bread - Calabrese Baguette', 72);
insert into orders (order_id, product_name, person_id) values (282, 'Marjoram - Dried, Rubbed', 866);
insert into orders (order_id, product_name, person_id) values (283, 'Browning Caramel Glace', 616);
insert into orders (order_id, product_name, person_id) values (284, 'Wine - Vineland Estate Semi - Dry', 501);
insert into orders (order_id, product_name, person_id) values (285, 'Juice - Ocean Spray Kiwi', 682);
insert into orders (order_id, product_name, person_id) values (286, 'Steampan - Foil', 352);
insert into orders (order_id, product_name, person_id) values (287, 'Pesto - Primerba, Paste', 929);
insert into orders (order_id, product_name, person_id) values (288, 'Wine - White, French Cross', 111);
insert into orders (order_id, product_name, person_id) values (289, 'Marjoram - Dried, Rubbed', 521);
insert into orders (order_id, product_name, person_id) values (290, 'Baking Soda', 564);
insert into orders (order_id, product_name, person_id) values (291, 'Table Cloth 54x72 White', 178);
insert into orders (order_id, product_name, person_id) values (292, 'Sage - Rubbed', 840);
insert into orders (order_id, product_name, person_id) values (293, 'Nutmeg - Ground', 599);
insert into orders (order_id, product_name, person_id) values (294, 'Rice Pilaf, Dry,package', 856);
insert into orders (order_id, product_name, person_id) values (295, 'Tomatoes - Vine Ripe, Red', 181);
insert into orders (order_id, product_name, person_id) values (296, 'Jameson - Irish Whiskey', 949);
insert into orders (order_id, product_name, person_id) values (297, 'Lobak', 416);
insert into orders (order_id, product_name, person_id) values (298, 'Bread - Hamburger Buns', 588);
insert into orders (order_id, product_name, person_id) values (299, 'Icecream Cone - Areo Chocolate', 117);
insert into orders (order_id, product_name, person_id) values (300, 'Pants Custom Dry Clean', 473);
insert into orders (order_id, product_name, person_id) values (301, 'Wine - Montecillo Rioja Crianza', 129);
insert into orders (order_id, product_name, person_id) values (302, 'Chickensplit Half', 912);
insert into orders (order_id, product_name, person_id) values (303, 'Rolled Oats', 960);
insert into orders (order_id, product_name, person_id) values (304, 'Nantucket Apple Juice', 813);
insert into orders (order_id, product_name, person_id) values (305, 'Brownies - Two Bite, Chocolate', 455);
insert into orders (order_id, product_name, person_id) values (306, 'Papayas', 998);
insert into orders (order_id, product_name, person_id) values (307, 'Lotus Rootlets - Canned', 244);
insert into orders (order_id, product_name, person_id) values (308, 'Napkin - Beverge, White 2 - Ply', 775);
insert into orders (order_id, product_name, person_id) values (309, 'Nantucket - Pomegranate Pear', 270);
insert into orders (order_id, product_name, person_id) values (310, 'Juice - Ocean Spray Kiwi', 19);
insert into orders (order_id, product_name, person_id) values (311, 'Absolut Citron', 319);
insert into orders (order_id, product_name, person_id) values (312, 'Calypso - Lemonade', 25);
insert into orders (order_id, product_name, person_id) values (313, 'Peas - Frozen', 298);
insert into orders (order_id, product_name, person_id) values (314, 'Wine - Remy Pannier Rose', 731);
insert into orders (order_id, product_name, person_id) values (315, 'Oil - Macadamia', 767);
insert into orders (order_id, product_name, person_id) values (316, 'Chocolate - Dark', 624);
insert into orders (order_id, product_name, person_id) values (317, 'Wanton Wrap', 491);
insert into orders (order_id, product_name, person_id) values (318, 'Parsley - Fresh', 919);
insert into orders (order_id, product_name, person_id) values (319, 'Pie Pecan', 737);
insert into orders (order_id, product_name, person_id) values (320, 'Spice - Pepper Portions', 494);
insert into orders (order_id, product_name, person_id) values (321, 'Vodka - Smirnoff', 386);
insert into orders (order_id, product_name, person_id) values (322, 'Veal - Inside', 101);
insert into orders (order_id, product_name, person_id) values (323, 'Teriyaki Sauce', 569);

insert into orders (order_id, product_name, person_id) values (325, 'Pasta - Rotini, Colour, Dry', 560);
insert into orders (order_id, product_name, person_id) values (326, 'Wine - Riesling Dr. Pauly', 545);
insert into orders (order_id, product_name, person_id) values (327, 'Bacon Strip Precooked', 104);
insert into orders (order_id, product_name, person_id) values (328, 'Cake - Miini Cheesecake Cherry', 649);
insert into orders (order_id, product_name, person_id) values (329, 'Guinea Fowl', 461);
insert into orders (order_id, product_name, person_id) values (330, 'Beer - Muskoka Cream Ale', 534);
insert into orders (order_id, product_name, person_id) values (331, 'Bacardi Breezer - Strawberry', 22);
insert into orders (order_id, product_name, person_id) values (332, 'Ice - Clear, 300 Lb For Carving', 356);
insert into orders (order_id, product_name, person_id) values (333, 'Roe - White Fish', 500);
insert into orders (order_id, product_name, person_id) values (334, 'Red Currant Jelly', 124);
insert into orders (order_id, product_name, person_id) values (335, 'Pork - Back Ribs', 360);
insert into orders (order_id, product_name, person_id) values (336, 'Pork - European Side Bacon', 384);
insert into orders (order_id, product_name, person_id) values (337, 'Chips Potato Salt Vinegar 43g', 862);
insert into orders (order_id, product_name, person_id) values (338, 'Wine - Magnotta - Belpaese', 552);
insert into orders (order_id, product_name, person_id) values (339, 'Cookies Cereal Nut', 815);
insert into orders (order_id, product_name, person_id) values (340, 'Coffee Beans - Chocolate', 935);
insert into orders (order_id, product_name, person_id) values (341, 'Wine - White, Mosel Gold', 920);
insert into orders (order_id, product_name, person_id) values (342, 'Dish Towel', 425);
insert into orders (order_id, product_name, person_id) values (343, 'Clam - Cherrystone', 488);
insert into orders (order_id, product_name, person_id) values (344, 'Liquid Aminios Acid - Braggs', 720);
insert into orders (order_id, product_name, person_id) values (345, 'Coffee - Hazelnut Cream', 705);
insert into orders (order_id, product_name, person_id) values (346, 'Buttons', 419);
insert into orders (order_id, product_name, person_id) values (347, 'Onions Granulated', 686);
insert into orders (order_id, product_name, person_id) values (348, 'Mcguinness - Blue Curacao', 734);
insert into orders (order_id, product_name, person_id) values (349, 'Beef - Tongue, Cooked', 732);
insert into orders (order_id, product_name, person_id) values (350, 'Halibut - Fletches', 279);
insert into orders (order_id, product_name, person_id) values (351, 'Muffin - Carrot Individual Wrap', 654);
insert into orders (order_id, product_name, person_id) values (352, 'Apple - Delicious, Golden', 883);
insert into orders (order_id, product_name, person_id) values (353, 'Sauce - Thousand Island', 851);
insert into orders (order_id, product_name, person_id) values (354, 'Cocoa Powder - Dutched', 834);
insert into orders (order_id, product_name, person_id) values (355, 'Raspberries - Frozen', 641);
insert into orders (order_id, product_name, person_id) values (356, 'Petit Baguette', 981);
insert into orders (order_id, product_name, person_id) values (357, 'Mustard - Pommery', 62);
insert into orders (order_id, product_name, person_id) values (358, 'Mushroom - White Button', 742);
insert into orders (order_id, product_name, person_id) values (359, 'Lentils - Green Le Puy', 497);
insert into orders (order_id, product_name, person_id) values (360, 'Sugar - Fine', 7);
insert into orders (order_id, product_name, person_id) values (361, 'Pastry - Chocolate Marble Tea', 472);
insert into orders (order_id, product_name, person_id) values (362, 'Gatorade - Xfactor Berry', 793);
insert into orders (order_id, product_name, person_id) values (363, 'Wine - Beaujolais Villages', 772);
insert into orders (order_id, product_name, person_id) values (364, 'Beer - Blue', 737);
insert into orders (order_id, product_name, person_id) values (365, 'Ginger - Fresh', 762);
insert into orders (order_id, product_name, person_id) values (366, 'Sauce - Bernaise, Mix', 605);
insert into orders (order_id, product_name, person_id) values (367, 'Foam Tray S2', 402);

insert into orders (order_id, product_name, person_id) values (369, 'Beer - Original Organic Lager', 482);
insert into orders (order_id, product_name, person_id) values (370, 'Piping Jelly - All Colours', 543);
insert into orders (order_id, product_name, person_id) values (371, 'Tendrils - Baby Pea, Organic', 202);
insert into orders (order_id, product_name, person_id) values (372, 'Bread - Dark Rye', 582);
insert into orders (order_id, product_name, person_id) values (373, 'Ice Cream - Life Savers', 366);
insert into orders (order_id, product_name, person_id) values (374, 'Nut - Almond, Blanched, Whole', 267);
insert into orders (order_id, product_name, person_id) values (375, 'Sour Puss Raspberry', 13);
insert into orders (order_id, product_name, person_id) values (376, 'Yams', 836);
insert into orders (order_id, product_name, person_id) values (377, 'Pastry - Lemon Danish - Mini', 948);
insert into orders (order_id, product_name, person_id) values (378, 'Lemon Pepper', 317);
insert into orders (order_id, product_name, person_id) values (379, 'Wine - Gato Negro Cabernet', 628);
insert into orders (order_id, product_name, person_id) values (380, 'Food Colouring - Pink', 376);
insert into orders (order_id, product_name, person_id) values (381, 'Potatoes - Idaho 100 Count', 68);
insert into orders (order_id, product_name, person_id) values (382, 'Bread - Pullman, Sliced', 852);
insert into orders (order_id, product_name, person_id) values (383, 'Pears - Fiorelle', 374);
insert into orders (order_id, product_name, person_id) values (384, 'Juice - Orangina', 364);
insert into orders (order_id, product_name, person_id) values (385, 'Rosemary - Fresh', 457);
insert into orders (order_id, product_name, person_id) values (386, 'Table Cloth 62x120 White', 141);
insert into orders (order_id, product_name, person_id) values (387, 'Syrup - Chocolate', 962);
insert into orders (order_id, product_name, person_id) values (388, 'Radish', 641);
insert into orders (order_id, product_name, person_id) values (389, 'Lamb Leg - Bone - In Nz', 255);
insert into orders (order_id, product_name, person_id) values (390, 'Flour Dark Rye', 258);
insert into orders (order_id, product_name, person_id) values (391, 'Dawn Professionl Pot And Pan', 641);
insert into orders (order_id, product_name, person_id) values (392, 'Southern Comfort', 531);
insert into orders (order_id, product_name, person_id) values (393, 'Table Cloth 90x90 White', 624);
insert into orders (order_id, product_name, person_id) values (394, 'Wine - Cahors Ac 2000, Clos', 323);
insert into orders (order_id, product_name, person_id) values (395, 'Vinegar - White', 26);
insert into orders (order_id, product_name, person_id) values (396, 'Ginger - Fresh', 756);
insert into orders (order_id, product_name, person_id) values (397, 'Muffin Mix - Chocolate Chip', 520);
insert into orders (order_id, product_name, person_id) values (398, 'Huck Towels White', 822);
insert into orders (order_id, product_name, person_id) values (399, 'Coffee - Hazelnut Cream', 58);
insert into orders (order_id, product_name, person_id) values (400, 'True - Vue Containers', 324);
insert into orders (order_id, product_name, person_id) values (401, 'Pork - Backs - Boneless', 947);
insert into orders (order_id, product_name, person_id) values (402, 'Cookies Almond Hazelnut', 738);
insert into orders (order_id, product_name, person_id) values (403, 'Chicken - Breast, 5 - 7 Oz', 918);
insert into orders (order_id, product_name, person_id) values (404, 'Soup - Campbells Broccoli', 385);
insert into orders (order_id, product_name, person_id) values (405, 'Apples - Spartan', 817);
insert into orders (order_id, product_name, person_id) values (406, 'Napkin - Beverage 1 Ply', 921);
insert into orders (order_id, product_name, person_id) values (407, 'Tomato Puree', 999);
insert into orders (order_id, product_name, person_id) values (408, 'Buttons', 644);
insert into orders (order_id, product_name, person_id) values (409, 'Brandy - Orange, Mc Guiness', 189);
insert into orders (order_id, product_name, person_id) values (410, 'Potatoes - Peeled', 413);
insert into orders (order_id, product_name, person_id) values (411, 'Lentils - Green, Dry', 350);
insert into orders (order_id, product_name, person_id) values (412, 'Orange Roughy 4/6 Oz', 18);
insert into orders (order_id, product_name, person_id) values (413, 'Soup - Cream Of Broccoli', 844);
insert into orders (order_id, product_name, person_id) values (414, 'Beef Cheek Fresh', 707);
insert into orders (order_id, product_name, person_id) values (415, 'Jack Daniels', 148);
insert into orders (order_id, product_name, person_id) values (416, 'Tomatoes', 614);
insert into orders (order_id, product_name, person_id) values (417, 'Nut - Chestnuts, Whole', 41);
insert into orders (order_id, product_name, person_id) values (418, 'Coriander - Ground', 427);
insert into orders (order_id, product_name, person_id) values (419, 'Lamb - Shoulder, Boneless', 185);
insert into orders (order_id, product_name, person_id) values (420, 'Squash - Pattypan, Yellow', 212);
insert into orders (order_id, product_name, person_id) values (421, 'Ranchero - Primerba, Paste', 797);
insert into orders (order_id, product_name, person_id) values (422, 'Muffin Mix - Banana Nut', 146);
insert into orders (order_id, product_name, person_id) values (423, 'Soap - Hand Soap', 114);
insert into orders (order_id, product_name, person_id) values (424, 'Chicken Breast Halal', 454);
insert into orders (order_id, product_name, person_id) values (425, 'The Pop Shoppe - Black Cherry', 926);
insert into orders (order_id, product_name, person_id) values (426, 'Beans - Yellow', 603);
insert into orders (order_id, product_name, person_id) values (427, 'Tea - Herbal I Love Lemon', 369);
insert into orders (order_id, product_name, person_id) values (428, 'Bread - French Baquette', 810);
insert into orders (order_id, product_name, person_id) values (429, 'Shrimp - 16/20, Peeled Deviened', 408);
insert into orders (order_id, product_name, person_id) values (430, 'Flour - So Mix Cake White', 938);
insert into orders (order_id, product_name, person_id) values (431, 'Flower - Leather Leaf Fern', 699);
insert into orders (order_id, product_name, person_id) values (432, 'Ostrich - Fan Fillet', 878);
insert into orders (order_id, product_name, person_id) values (433, 'Cattail Hearts', 214);
insert into orders (order_id, product_name, person_id) values (434, 'Beef - Cooked, Corned', 671);
insert into orders (order_id, product_name, person_id) values (435, 'Cheese - Comtomme', 425);
insert into orders (order_id, product_name, person_id) values (436, 'Wine - Barolo Fontanafredda', 264);
insert into orders (order_id, product_name, person_id) values (437, 'Wine - Red Oakridge Merlot', 677);
insert into orders (order_id, product_name, person_id) values (438, 'Tomatoes - Cherry, Yellow', 630);
insert into orders (order_id, product_name, person_id) values (439, 'Cheese - Swiss', 227);
insert into orders (order_id, product_name, person_id) values (440, 'Beans - Kidney White', 595);
insert into orders (order_id, product_name, person_id) values (441, 'Prunes - Pitted', 346);
insert into orders (order_id, product_name, person_id) values (442, 'Pasta - Rotini, Dry', 530);
insert into orders (order_id, product_name, person_id) values (443, 'Mushroom - Chanterelle, Dry', 599);
insert into orders (order_id, product_name, person_id) values (444, 'Cheese - La Sauvagine', 870);
insert into orders (order_id, product_name, person_id) values (445, 'Bread - Roll, Whole Wheat', 933);
insert into orders (order_id, product_name, person_id) values (446, 'Pasta - Linguini, Dry', 908);
insert into orders (order_id, product_name, person_id) values (447, 'Ham Black Forest', 41);
insert into orders (order_id, product_name, person_id) values (448, 'Wine - White, Gewurtzraminer', 889);
insert into orders (order_id, product_name, person_id) values (449, 'Cheese - Ermite Bleu', 14);
insert into orders (order_id, product_name, person_id) values (450, 'Cheese - Gorgonzola', 199);
insert into orders (order_id, product_name, person_id) values (451, 'Appetizer - Lobster Phyllo Roll', 321);
insert into orders (order_id, product_name, person_id) values (452, 'Pepper - Pablano', 624);
insert into orders (order_id, product_name, person_id) values (453, 'Nacho Chips', 254);
insert into orders (order_id, product_name, person_id) values (454, 'Ketchup - Tomato', 974);
insert into orders (order_id, product_name, person_id) values (455, 'Orange - Canned, Mandarin', 130);
insert into orders (order_id, product_name, person_id) values (456, 'Buttons', 521);
insert into orders (order_id, product_name, person_id) values (457, 'Rice - Wild', 805);
insert into orders (order_id, product_name, person_id) values (458, 'Oil - Food, Lacquer Spray', 715);
insert into orders (order_id, product_name, person_id) values (459, 'Juice - Lime', 703);
insert into orders (order_id, product_name, person_id) values (460, 'Rice - Long Grain', 267);
insert into orders (order_id, product_name, person_id) values (461, 'Pomello', 632);
insert into orders (order_id, product_name, person_id) values (462, 'Wine - Segura Viudas Aria Brut', 515);
insert into orders (order_id, product_name, person_id) values (463, 'Dried Cranberries', 196);
insert into orders (order_id, product_name, person_id) values (464, 'Mushroom - White Button', 445);
insert into orders (order_id, product_name, person_id) values (465, 'Cod - Fillets', 810);
insert into orders (order_id, product_name, person_id) values (466, 'Syrup - Kahlua Chocolate', 725);
insert into orders (order_id, product_name, person_id) values (467, 'Bread - Roll, Whole Wheat', 525);
insert into orders (order_id, product_name, person_id) values (468, 'Beef - Tenderloin - Aa', 162);
insert into orders (order_id, product_name, person_id) values (469, 'Oil - Olive, Extra Virgin', 611);
insert into orders (order_id, product_name, person_id) values (470, 'Soup Campbells Split Pea And Ham', 446);
insert into orders (order_id, product_name, person_id) values (471, 'Beer - Molson Excel', 358);
insert into orders (order_id, product_name, person_id) values (472, 'Mushroom - Shitake, Dry', 861);
insert into orders (order_id, product_name, person_id) values (473, 'Veal - Striploin', 223);
insert into orders (order_id, product_name, person_id) values (474, 'Trout - Rainbow, Frozen', 233);
insert into orders (order_id, product_name, person_id) values (475, 'Cookie Choc', 145);
insert into orders (order_id, product_name, person_id) values (476, 'Broom And Brush Rack Black', 314);
insert into orders (order_id, product_name, person_id) values (477, 'Sauce - Balsamic Viniagrette', 24);
insert into orders (order_id, product_name, person_id) values (478, 'Oven Mitts 17 Inch', 570);
insert into orders (order_id, product_name, person_id) values (479, 'Cheese - Provolone', 979);
insert into orders (order_id, product_name, person_id) values (480, 'Ecolab - Balanced Fusion', 597);
insert into orders (order_id, product_name, person_id) values (481, 'Tea - Vanilla Chai', 447);
insert into orders (order_id, product_name, person_id) values (482, 'Muffin Mix - Chocolate Chip', 967);
insert into orders (order_id, product_name, person_id) values (483, 'Tea - Herbal Sweet Dreams', 260);
insert into orders (order_id, product_name, person_id) values (484, 'Steampan Lid', 808);
insert into orders (order_id, product_name, person_id) values (485, 'Magnotta - Bel Paese White', 187);
insert into orders (order_id, product_name, person_id) values (486, 'Cheese - Le Cheve Noir', 891);
insert into orders (order_id, product_name, person_id) values (487, 'Shrimp - 31/40', 17);
insert into orders (order_id, product_name, person_id) values (488, 'Wine - Barolo Fontanafredda', 825);
insert into orders (order_id, product_name, person_id) values (489, 'Dried Apple', 86);
insert into orders (order_id, product_name, person_id) values (490, 'Haggis', 573);
insert into orders (order_id, product_name, person_id) values (491, 'Wine - Zinfandel California 2002', 839);
insert into orders (order_id, product_name, person_id) values (492, 'Bread - White Epi Baguette', 682);
insert into orders (order_id, product_name, person_id) values (493, 'Tomatoes - Plum, Canned', 684);
insert into orders (order_id, product_name, person_id) values (494, 'Juice Peach Nectar', 416);
insert into orders (order_id, product_name, person_id) values (495, 'Foil Cont Round', 313);
insert into orders (order_id, product_name, person_id) values (496, 'Juice - Grape, White', 833);
insert into orders (order_id, product_name, person_id) values (497, 'Lamb - Whole, Frozen', 346);
insert into orders (order_id, product_name, person_id) values (498, 'Magnotta Bel Paese Red', 930);
insert into orders (order_id, product_name, person_id) values (499, 'Scallops 60/80 Iqf', 787);
insert into orders (order_id, product_name, person_id) values (500, 'Carrots - Purple, Organic', 34);
insert into orders (order_id, product_name, person_id) values (501, 'Barley - Pearl', 801);
insert into orders (order_id, product_name, person_id) values (502, 'Mangoes', 516);
insert into orders (order_id, product_name, person_id) values (503, 'Wine - Puligny Montrachet A.', 161);
insert into orders (order_id, product_name, person_id) values (504, 'Wine - Mas Chicet Rose, Vintage', 76);
insert into orders (order_id, product_name, person_id) values (505, 'Wonton Wrappers', 622);
insert into orders (order_id, product_name, person_id) values (506, 'Bouq All Italian - Primerba', 245);
insert into orders (order_id, product_name, person_id) values (507, 'Longos - Grilled Salmon With Bbq', 699);
insert into orders (order_id, product_name, person_id) values (508, 'Water Chestnut - Canned', 627);
insert into orders (order_id, product_name, person_id) values (509, 'Spice - Chili Powder Mexican', 842);
insert into orders (order_id, product_name, person_id) values (510, 'Cheese - Valancey', 117);
insert into orders (order_id, product_name, person_id) values (511, 'Sprite, Diet - 355ml', 336);
insert into orders (order_id, product_name, person_id) values (512, 'Alize Red Passion', 426);
insert into orders (order_id, product_name, person_id) values (513, 'Kale - Red', 677);
insert into orders (order_id, product_name, person_id) values (514, 'Extract - Raspberry', 525);
insert into orders (order_id, product_name, person_id) values (515, 'Cheese - Pont Couvert', 714);
insert into orders (order_id, product_name, person_id) values (516, 'Beef Wellington', 604);
insert into orders (order_id, product_name, person_id) values (517, 'Corn Syrup', 903);
insert into orders (order_id, product_name, person_id) values (518, 'Tofu - Soft', 260);
insert into orders (order_id, product_name, person_id) values (519, 'Lettuce - Romaine', 956);
insert into orders (order_id, product_name, person_id) values (520, 'Wine - White, Mosel Gold', 660);
insert into orders (order_id, product_name, person_id) values (521, 'Veal Inside - Provimi', 362);
insert into orders (order_id, product_name, person_id) values (522, 'Langers - Ruby Red Grapfruit', 939);
insert into orders (order_id, product_name, person_id) values (523, 'Longos - Grilled Salmon With Bbq', 886);
insert into orders (order_id, product_name, person_id) values (524, 'Cookies - Fortune', 930);
insert into orders (order_id, product_name, person_id) values (525, 'Sprite, Diet - 355ml', 594);
insert into orders (order_id, product_name, person_id) values (526, 'Butter Sweet', 920);
insert into orders (order_id, product_name, person_id) values (527, 'Ecolab - Hand Soap Form Antibac', 183);
insert into orders (order_id, product_name, person_id) values (528, 'Coffee - French Vanilla Frothy', 728);
insert into orders (order_id, product_name, person_id) values (529, 'Tomato - Peeled Italian Canned', 737);
insert into orders (order_id, product_name, person_id) values (530, 'Sauce - Cranberry', 885);
insert into orders (order_id, product_name, person_id) values (531, 'Cherries - Bing, Canned', 235);
insert into orders (order_id, product_name, person_id) values (532, 'Pasta - Bauletti, Chicken White', 285);
insert into orders (order_id, product_name, person_id) values (533, 'Nantucket - Orange Mango Cktl', 726);
insert into orders (order_id, product_name, person_id) values (534, 'Loquat', 503);
insert into orders (order_id, product_name, person_id) values (535, 'Pasta - Cheese / Spinach Bauletti', 922);
insert into orders (order_id, product_name, person_id) values (536, 'French Pastries', 533);
insert into orders (order_id, product_name, person_id) values (537, 'Sage Derby', 576);
insert into orders (order_id, product_name, person_id) values (538, 'Bay Leaf Ground', 92);
insert into orders (order_id, product_name, person_id) values (539, 'Filter - Coffee', 827);
insert into orders (order_id, product_name, person_id) values (540, 'Peas - Pigeon, Dry', 553);
insert into orders (order_id, product_name, person_id) values (541, 'Lamb - Whole, Fresh', 259);
insert into orders (order_id, product_name, person_id) values (542, 'Muffin Batt - Blueberry Passion', 373);
insert into orders (order_id, product_name, person_id) values (543, 'Oil - Olive Bertolli', 734);
insert into orders (order_id, product_name, person_id) values (544, 'Chocolate Liqueur - Godet White', 519);
insert into orders (order_id, product_name, person_id) values (545, 'Juice Peach Nectar', 256);
insert into orders (order_id, product_name, person_id) values (546, 'Shrimp - Black Tiger 8 - 12', 143);
insert into orders (order_id, product_name, person_id) values (547, 'Wine - Magnotta, White', 818);
insert into orders (order_id, product_name, person_id) values (548, 'Beets', 858);
insert into orders (order_id, product_name, person_id) values (549, 'Tomato - Tricolor Cherry', 62);
insert into orders (order_id, product_name, person_id) values (550, 'Honey - Comb', 542);
insert into orders (order_id, product_name, person_id) values (551, 'Pastry - Lemon Danish - Mini', 18);
insert into orders (order_id, product_name, person_id) values (552, 'Eel Fresh', 457);
insert into orders (order_id, product_name, person_id) values (553, 'Eggs - Extra Large', 290);
insert into orders (order_id, product_name, person_id) values (554, 'Puree - Guava', 388);
insert into orders (order_id, product_name, person_id) values (555, 'Cheese - La Sauvagine', 107);
insert into orders (order_id, product_name, person_id) values (556, 'Bagel - Plain', 779);
insert into orders (order_id, product_name, person_id) values (557, 'Clementine', 512);
insert into orders (order_id, product_name, person_id) values (558, 'Wine - Red, Cooking', 341);
insert into orders (order_id, product_name, person_id) values (559, 'Chinese Foods - Plain Fried Rice', 577);
insert into orders (order_id, product_name, person_id) values (560, 'Longos - Burritos', 635);
insert into orders (order_id, product_name, person_id) values (561, 'Shrimp - 150 - 250', 862);
insert into orders (order_id, product_name, person_id) values (562, 'Piping Jelly - All Colours', 12);
insert into orders (order_id, product_name, person_id) values (563, 'Doilies - 8, Paper', 700);
insert into orders (order_id, product_name, person_id) values (564, 'Pepper - Cayenne', 848);
insert into orders (order_id, product_name, person_id) values (565, 'Napkin White', 545);
insert into orders (order_id, product_name, person_id) values (566, 'Cup - 6oz, Foam', 421);
insert into orders (order_id, product_name, person_id) values (567, 'Prunes - Pitted', 341);
insert into orders (order_id, product_name, person_id) values (568, 'Lamb - Whole, Frozen', 526);
insert into orders (order_id, product_name, person_id) values (569, 'Bread Foccacia Whole', 291);
insert into orders (order_id, product_name, person_id) values (570, 'Absolut Citron', 774);
insert into orders (order_id, product_name, person_id) values (571, 'Onions Granulated', 935);
insert into orders (order_id, product_name, person_id) values (572, 'Pastry - Carrot Muffin - Mini', 260);
insert into orders (order_id, product_name, person_id) values (573, 'Spinach - Spinach Leaf', 550);
insert into orders (order_id, product_name, person_id) values (574, 'Lettuce - Treviso', 733);
insert into orders (order_id, product_name, person_id) values (575, 'Veal - Eye Of Round', 97);
insert into orders (order_id, product_name, person_id) values (576, 'Cheese - Cheddar, Old White', 280);
insert into orders (order_id, product_name, person_id) values (577, 'Soup - Beef, Base Mix', 830);
insert into orders (order_id, product_name, person_id) values (578, 'Island Oasis - Banana Daiquiri', 578);
insert into orders (order_id, product_name, person_id) values (579, 'Pan Grease', 697);
insert into orders (order_id, product_name, person_id) values (580, 'Sunflower Seed Raw', 499);
insert into orders (order_id, product_name, person_id) values (581, 'Sauce - Cranberry', 984);
insert into orders (order_id, product_name, person_id) values (582, 'Cookies - Assorted', 418);
insert into orders (order_id, product_name, person_id) values (583, 'Cakes Assorted', 756);
insert into orders (order_id, product_name, person_id) values (584, 'Seedlings - Clamshell', 901);
insert into orders (order_id, product_name, person_id) values (585, 'Crackers - Water', 164);
insert into orders (order_id, product_name, person_id) values (586, 'Bagel - Sesame Seed Presliced', 856);
insert into orders (order_id, product_name, person_id) values (587, 'Clams - Littleneck, Whole', 521);
insert into orders (order_id, product_name, person_id) values (588, 'Thyme - Fresh', 494);
insert into orders (order_id, product_name, person_id) values (589, 'Chips Potato All Dressed - 43g', 619);
insert into orders (order_id, product_name, person_id) values (590, 'Rosemary - Fresh', 566);
insert into orders (order_id, product_name, person_id) values (591, 'Bread - Burger', 131);
insert into orders (order_id, product_name, person_id) values (592, 'Salmon Steak - Cohoe 6 Oz', 780);
insert into orders (order_id, product_name, person_id) values (593, 'Grapes - Green', 789);
insert into orders (order_id, product_name, person_id) values (594, 'Ice Cream - Chocolate', 742);
insert into orders (order_id, product_name, person_id) values (595, 'Yogurt - Strawberry, 175 Gr', 531);
insert into orders (order_id, product_name, person_id) values (596, 'Cucumber - English', 929);
insert into orders (order_id, product_name, person_id) values (597, 'Croissant, Raw - Mini', 690);
insert into orders (order_id, product_name, person_id) values (598, 'Wine - White, Colubia Cresh', 143);
insert into orders (order_id, product_name, person_id) values (599, 'Jolt Cola', 579);
insert into orders (order_id, product_name, person_id) values (600, 'Bread - Pita, Mini', 949);
insert into orders (order_id, product_name, person_id) values (601, 'Ecolab - Ster Bac', 891);
insert into orders (order_id, product_name, person_id) values (602, 'Muskox - French Rack', 633);
insert into orders (order_id, product_name, person_id) values (603, 'Coffee Caramel Biscotti', 402);
insert into orders (order_id, product_name, person_id) values (604, 'Pasta - Cheese / Spinach Bauletti', 739);
insert into orders (order_id, product_name, person_id) values (605, 'Isomalt', 507);
insert into orders (order_id, product_name, person_id) values (606, 'Shrimp - Black Tiger 6 - 8', 501);
insert into orders (order_id, product_name, person_id) values (607, 'Bread - Pita', 786);
insert into orders (order_id, product_name, person_id) values (608, 'Chilli Paste, Hot Sambal Oelek', 862);
insert into orders (order_id, product_name, person_id) values (609, 'Sprouts - Corn', 303);
insert into orders (order_id, product_name, person_id) values (610, 'Cheese - Comtomme', 539);
insert into orders (order_id, product_name, person_id) values (611, 'Eggwhite Frozen', 105);
insert into orders (order_id, product_name, person_id) values (612, 'Lady Fingers', 817);
insert into orders (order_id, product_name, person_id) values (613, 'Sauce - Demi Glace', 724);
insert into orders (order_id, product_name, person_id) values (614, 'Flax Seed', 84);
insert into orders (order_id, product_name, person_id) values (615, 'Cheese Cheddar Processed', 1);
insert into orders (order_id, product_name, person_id) values (616, 'Pail With Metal Handle 16l White', 781);
insert into orders (order_id, product_name, person_id) values (618, 'Roe - Lump Fish, Red', 458);
insert into orders (order_id, product_name, person_id) values (619, 'Bagel - Ched Chs Presliced', 573);
insert into orders (order_id, product_name, person_id) values (620, 'Cream - 18%', 744);
insert into orders (order_id, product_name, person_id) values (621, 'Samosa - Veg', 989);

